backend/expense/urls.py
from django.urls import path

from . import views

app_name = 'expense'
urlpatterns = [
    path('', views.index, name='index'),
    path('owing/', views.owing, name="owing"),
    path('pay/<uuid:anon_link>', views.PayAnonView.as_view()),
    path('owed/', views.owed, name="owed"),
    path('<int:expense_id>', views.details, name='details'),
    path('<int:group_id>/new/', views.new, name='new'),
    path('<int:expense_id>/pay/', views.pay, name='pay'),
    path('<int:expense_id>/delete/', views.delete, name='delete'),
    path('payments/', views.getPayments, name='getPayments')
]

backend/group/urls.py
from django.urls import path

from . import views

app_name = 'group'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:group_id>/', views.detail, name='detail'),
    path('<int:group_id>/add_friend', views.add_friend, name='add_friend'),
    path('create/', views.create, name='create'),
    path('<int:group_id>/delete', views.delete, name='delete')
]

backend/moneySplit/urls.py
from django.contrib import admin
from django.urls import include, path

from . import views
app_name = 'root'
urlpatterns = [
    path('user/', include('user.urls')),
    path('expense/', include('expense.urls')),
    path('group/', include('group.urls')),
    path('admin/', admin.site.urls),
    path('', views.index, name="index")
]

backend/user/urls.py
from django.urls import path

from . import views
from django.contrib import admin
from django.urls import path, include
from rest_framework_jwt.views import obtain_jwt_token, refresh_jwt_token, verify_jwt_token

app_name = 'user'
urlpatterns = [
    # path('', views.index, name='index'),
    path('token-auth/', obtain_jwt_token),
    path('refresh/', refresh_jwt_token),
    path('api-token-verify/', verify_jwt_token),
    path('current_user/', views.get_current_user),
    path('create/', views.CreateUserView.as_view()),
    path('update/', views.update),
    path('new/', views.new, name="new"),
    path('login/', views.userLogin, name="login"),
    path('logout/', views.userLogout, name="logout"),
    path('info/', views.info, name="info")
]

backend/expense/models.py
import uuid

from django.contrib.auth.models import User
from django.db import models

from group.models import Group


# Create your models here.
class Expense(models.Model):
    # Add some choices later
    CATEGORIES_CHOICES = []

    group = models.ForeignKey(Group, on_delete=models.CASCADE, null=True)
    users = models.ManyToManyField(User)
    name = models.CharField(max_length=255)
    amount = models.DecimalField(max_digits=7, decimal_places=2)  # Current amount
    bill_amount = models.DecimalField(max_digits=7, decimal_places=2)  # Original amount
    date = models.DateField()
    notes = models.TextField(max_length=500, blank=True, null=True)
    category = models.CharField(max_length=50, choices=CATEGORIES_CHOICES, blank=True, null=True)
    # the person who paid the bill
    paid_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name="paid_by")
    anon_link = models.UUIDField(unique=True, default=uuid.uuid4, editable=False)


class ExpenseEntry(models.Model):
    # the person who created the expense
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    # which group the expense belongs to
    groupExpense = models.ForeignKey(Expense, on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=255)
    amount = models.DecimalField(max_digits=7, decimal_places=2)
    date = models.DateField(auto_now_add=True)


class PaymentHistory(models.Model):
    # the person who created the expense
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = name = models.CharField(max_length=255)
    # which individual expense that this payment is made for
    inidividualExpense = models.ForeignKey(ExpenseEntry, on_delete=models.CASCADE, null=True)
    groupExpense = models.ForeignKey(Expense, on_delete=models.CASCADE, null=True)
    amount = models.DecimalField(max_digits=7, decimal_places=2)
    date = models.DateField(auto_now_add=True)

backend/group/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse


# Create your models here.
# from expense.models import Expense

class Group(models.Model):
    users = models.ManyToManyField(User)
    name = models.CharField(max_length=255)
    description = models.TextField(max_length=500, null=True)
    dateCreated = models.DateTimeField('date created', auto_now=True)
    groupMessage = models.TextField(null=True, blank=True)

    def __str__(self):
        return "group name: %s, date created: %s" % (self.name, str(self.dateCreated))

    # def get_absolute_url(self):
    # return reverse("index", kwargs={"id": self.id})

    # each expense has a group
    # create a new group
    # add users to group
    # display expenses 
    # page -> list groups with a create group button
    # create group -> takes you to where you can create groups takes you back after ur done
    # click on a group, displays date, amount, and users

    # index - group name, expenses-> also link to create a new group
    # click on a group, displays date, amount, and users

backend/group/forms.py
from django import forms
from .models import Group


class GroupForm(forms.ModelForm):
    class Meta:
        model = Group
        fields = [
            'name',
            'description',
            'groupMessage'
        ]


class AddFriendForm(forms.Form):
    email = forms.EmailField(label='Enter email')

    def clean_email(self):
        email = self.cleaned_data['email'].lower()
        return email

backend/group/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.validators import validate_email
from django.http import HttpResponse, HttpResponseRedirect, Http404, JsonResponse
from django.shortcuts import render, get_object_or_404, reverse, redirect
from django.views.decorators.csrf import csrf_exempt

from rest_framework.response import Response
from rest_framework.decorators import api_view
from rest_framework import status
from .serializers import *

from user.models import UserProfile
from .models import Group
from .forms import GroupForm, AddFriendForm


@api_view(['GET'])
def index(request):
    if request.user.is_authenticated:
        userGroups = request.user.group_set.all()
        serializer = GroupSerializer(userGroups, many=True)
        return JsonResponse(serializer.data, safe=False)
    else:
        return HttpResponse('Unauthorized', status=401)


@api_view(['GET'])
def detail(request, group_id):
    if request.user.is_authenticated:
        group = get_object_or_404(Group, pk=group_id)
        if not group.users.filter(id=request.user.id).exists():
            raise Http404("Group not found")
        serializer = GroupSerializer(group)
        return JsonResponse(serializer.data)
    return Http404("Not found")


@api_view(['POST'])
def create(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            serializer = GroupSerializer(data=request.data)
            if serializer.is_valid():
                group = serializer.save()
                group.users.add(request.user)
                return Response(serializer.data, status=status.HTTP_201_CREATED)
            else:
                return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
        # else:
        #     form = GroupForm(request.POST)
        #     return render(request, 'group/create.html', {'form': form})
    else:
       return HttpResponse('Unauthorized', status=401)


@api_view(['POST'])
def add_friend(request, group_id):
    group = Group.objects.get(id=group_id)
    if request.method == "POST":
        user, is_new_user = User.objects.get_or_create(username=request.data.get('email'))
        group.users.add(user)
        if is_new_user:
            UserProfile.objects.create(user=user, is_active=False)
        group.save()
        serializer = GroupSerializer(group)
        return Response(serializer.data, status=status.HTTP_201_CREATED)
    return Http404("Not found")

@api_view(['DELETE'])
def delete(request, group_id):
    if request.user.is_authenticated:
        group = Group.objects.get(id=group_id)

        if request.user in group.users.all():

            group.delete()
            return Response()
        
        else:
            return Http404("Not found")
    
    else:
        return Http404("Not found")

backend/group/templates/group/create.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
<div class="container">
    <h1>New Group</h1>
  <form method = 'POST' action="{% url 'group:create' %}"> 
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-primary">Create Group</button>
  </form>
  </div>
{% endblock %}

backend/group/templates/group/detail.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <h1>{{ group.name }}</h1>
        <hr>
        <h2>Members</h2>
        {% for group_user in group.users.all %}
            <p>
                {{ group_user.username }}
            </p>
        {% endfor %}
        <form action="{% url 'group:add_friend' group.id %}" method="post">
            {% csrf_token %}
            <div class="inline">
                {{ add_friend_form }}
                <input type="submit" value="Add friend">
            </div>
        </form>
        {% if not group.expense_set.all %}
            <div>No expenses created yet. <a href="{% url 'expense:new' group.id %}">Create One</a></div>
        {% else %}

            <h2>Expenses</h2>
            <table style="width:50%">
                <tr>
                    <td>Name:</td>
                    <td>Amount:</td>
                    <td>Date:</td>
                </tr>
                    {% for expense in group.expense_set.all %}
                    <tr>
                        {% if expense.amount != 0 %}
                            <td>
                                <a href="{% url 'expense:details' expense.id %}">{{ expense.name }}</a>
                            </td>
                            <td>
                                {{ expense.amount }}
                            </td>
                            <td>
                                {{ expense.date }}
                            </td>
                        {% endif %}
                    </tr>
                    {% endfor %}
            </table>
            <a href="{% url 'expense:new' group.id %}">Add new expense</a>
        {% endif %}
    </div>
{% endblock %}

backend/group/templates/group/form_add_friend.html
<form action="{% url 'group:add_friend' group.id %}" method="post">

    {% csrf_token %}

    <div class="d-inline">
        <label>
            Email:
            <input name="user_email" type="text" placeholder="email@email.com">
        </label>
{#        or#}
{#        <label>#}
{#            Name:#}
{#            <input name="user_name" type="text" placeholder="John Doe">#}
{#        </label>#}
    </div>
    <input type="submit" value="Add friend">

</form>

backend/group/templates/group/index.html
{% extends 'base.html' %}

{% block content %}
    <h1>Here are all the groups that you are part of</h1>

    {% for group in group_list %}
    <p> <a href="{% url 'group:detail' group.id %}">
        {{group.id}} - {{group.name}}</a>
    </p>
    {% endfor %}
    <br>
    <div> <a href="{% url 'group:create' %}">Create new group</a></div>
    <br>
{% endblock %}