backend/expense/urls.py
from django.urls import path

from . import views

app_name = 'expense'
urlpatterns = [
    path('', views.index, name='index'),
    path('owing/', views.owing, name="owing"),
    path('pay/<uuid:anon_link>', views.PayAnonView.as_view()),
    path('owed/', views.owed, name="owed"),
    path('<int:expense_id>', views.details, name='details'),
    path('<int:group_id>/new/', views.new, name='new'),
    path('<int:expense_id>/pay/', views.pay, name='pay'),
    path('<int:expense_id>/delete/', views.delete, name='delete'),
    path('payments/', views.getPayments, name='getPayments')
]

backend/group/urls.py
from django.urls import path

from . import views

app_name = 'group'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:group_id>/', views.detail, name='detail'),
    path('<int:group_id>/add_friend', views.add_friend, name='add_friend'),
    path('create/', views.create, name='create'),
    path('<int:group_id>/delete', views.delete, name='delete')
]

backend/moneySplit/urls.py
from django.contrib import admin
from django.urls import include, path

from . import views
app_name = 'root'
urlpatterns = [
    path('user/', include('user.urls')),
    path('expense/', include('expense.urls')),
    path('group/', include('group.urls')),
    path('admin/', admin.site.urls),
    path('', views.index, name="index")
]

backend/user/urls.py
from django.urls import path

from . import views
from django.contrib import admin
from django.urls import path, include
from rest_framework_jwt.views import obtain_jwt_token, refresh_jwt_token, verify_jwt_token

app_name = 'user'
urlpatterns = [
    # path('', views.index, name='index'),
    path('token-auth/', obtain_jwt_token),
    path('refresh/', refresh_jwt_token),
    path('api-token-verify/', verify_jwt_token),
    path('current_user/', views.get_current_user),
    path('create/', views.CreateUserView.as_view()),
    path('update/', views.update),
    path('new/', views.new, name="new"),
    path('login/', views.userLogin, name="login"),
    path('logout/', views.userLogout, name="logout"),
    path('info/', views.info, name="info")
]

backend/expense/models.py
import uuid

from django.contrib.auth.models import User
from django.db import models

from group.models import Group


# Create your models here.
class Expense(models.Model):
    # Add some choices later
    CATEGORIES_CHOICES = []

    group = models.ForeignKey(Group, on_delete=models.CASCADE, null=True)
    users = models.ManyToManyField(User)
    name = models.CharField(max_length=255)
    amount = models.DecimalField(max_digits=7, decimal_places=2)  # Current amount
    bill_amount = models.DecimalField(max_digits=7, decimal_places=2)  # Original amount
    date = models.DateField()
    notes = models.TextField(max_length=500, blank=True, null=True)
    category = models.CharField(max_length=50, choices=CATEGORIES_CHOICES, blank=True, null=True)
    # the person who paid the bill
    paid_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name="paid_by")
    anon_link = models.UUIDField(unique=True, default=uuid.uuid4, editable=False)


class ExpenseEntry(models.Model):
    # the person who created the expense
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    # which group the expense belongs to
    groupExpense = models.ForeignKey(Expense, on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=255)
    amount = models.DecimalField(max_digits=7, decimal_places=2)
    date = models.DateField(auto_now_add=True)


class PaymentHistory(models.Model):
    # the person who created the expense
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = name = models.CharField(max_length=255)
    # which individual expense that this payment is made for
    inidividualExpense = models.ForeignKey(ExpenseEntry, on_delete=models.CASCADE, null=True)
    groupExpense = models.ForeignKey(Expense, on_delete=models.CASCADE, null=True)
    amount = models.DecimalField(max_digits=7, decimal_places=2)
    date = models.DateField(auto_now_add=True)

backend/moneySplit/views.py
from django.shortcuts import render, redirect

from expense.models import PaymentHistory
from group.models import Group


def index(request):
    if request.user.is_authenticated:
        groups = Group.objects.filter(users__in=[request.user])
        payments = PaymentHistory.objects.filter(user=request.user).order_by(
            '-pk')  # Reverse order of pk (ids) should give the most recent payments
        return render(request, 'root.html', {
            "groups": groups,
            "payments": payments
        })
    else:
        return redirect("user:new")

backend/moneySplit/templates/base.html
<!doctype html>
<head>
    <meta charset="utf-8">
    <title>Money Split</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
          integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
</head>

<body>

{% include "navbar.html" %}

{% block content %}
{% endblock %}

</body>

</html>

backend/moneySplit/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'index' %}">MoneySplit</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        {% if user.is_authenticated %}
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'index' %}">Dashboard</a>
                </li>
            </ul>
            <div>Welcome, <b>{{ user.username }}</b></div>
            <a class="ml-2 btn btn-primary" href="{% url 'user:logout' %}">Logout</a>
        {% else %}
            <div class="mr-auto"></div>
            <a class="btn btn-primary" href="{% url 'user:login' %}">Login</a>
            <a class="btn btn-primary ml-1" href="{% url 'user:new' %}">Sign Up</a>
        {% endif %}
    </div>
</nav>

backend/moneySplit/templates/root.html
{% extends "base.html" %}

{% block content %}
    <div class="container">
        <h1>Your Groups</h1>
        {% if not groups %}
            You are not part of any groups. <a href="{% url 'group:create' %}"> Create one!</a>
        {% else %}
            <ul>
                {% for g in groups %}
                    <li><a href="{% url 'group:detail' g.id %}">{{ g.name }}</a></li>
                {% endfor %}
            </ul>
            <a href="{% url 'group:create' %}">Create a new group</a>
        {% endif %}
        <h1>Recent Expenses</h1>
            <table style="width:50%">
                <tr>
                    <td>Name: </td>
                    <td>Amount: </td>
                    <td>Date: </td>
                </tr>
                {% for expenseEntry in user.expenseentry_set.all %}
                <tr>
                    {% if expenseEntry.amount != 0%}
                        <td>
                            <a href="{% url 'expense:details' expenseEntry.groupExpense.id %}">{{expenseEntry.name}} ({{ expenseEntry.groupExpense.group.name }})</a>
                        </td>
                        <td>
                            {{expenseEntry.amount}}
                        </td>
                        <td>
                            {{expenseEntry.date}}
                        </td>
                        <td>
                            <a href="{% url 'expense:pay' expenseEntry.id %}">Make Payment</a>
                        </td>
                    {% endif %}
                {% endfor %}
                </tr>
            </table>
    <h1>Your Payment History</h1>
        <table style="width:50%">
            <tr>
                <td>Payment for: </td>
                <td>Amount: </td>
                <td>Date: </td>
            </tr>
            {% for payment in payments %}
            <tr>
                <td>
                    {{payment.inidividualExpense.name}}
                </td>
                <td>
                    {{payment.amount}}
                </td>
                <td>
                    {{payment.date}}
                </td>
            {% endfor %}
            </tr>
        </table>
    </div>
{% endblock %}